config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get 'therapeute_pharmacienne_bioenergeticienne', to: 'pages#therapeute_pharmacienne_bioenergeticienne'
  get 'contact', to: 'pages#contact'
  get 'bioenergie', to: 'pages#bioenergie'
  get 'soins_a_distance', to:'pages#soins_a_distance'
  get 'animaux', to:'pages#animaux'
  get 'coaching', to:'pages#coaching'

  resources :soins, only: [:index, :show]
  resources :ateliers, only: [:index, :show]
  resources :actus, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actu.rb
class Actu < ApplicationRecord
  belongs_to :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atelier.rb
class Atelier < ApplicationRecord
  belongs_to :product, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :soins
  has_many :ateliers
  has_many :actualities
end

app/models/soin.rb
class Soin < ApplicationRecord
  belongs_to :product, optional: true

end

app/controllers/actus_controller.rb
class ActusController < ApplicationController
  def index
    @actus = Actu.all
  end

  def show
    @actus = Actu.find(params[:id])
  end

  private

  def actu_params
    params.require(:actu).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ateliers_controller.rb
class AteliersController < ApplicationController
  def index
    @ateliers = Atelier.all
  end

  def show
    @atelier = Atelier.find(params[:id])
  end

  private

  def atelier_params
    params.require(:atelier).permit(:name, :description, :tarif, :temoignagnes)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def therapeute_pharmacienne_bioenergeticienne

  end

  def contact

  end

  def bioenergie

  end

  def soins_a_distance

  end

  def animaux

  end

  def coaching

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :product_params, only: [:show]
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:name)
  end
end

app/controllers/soins_controller.rb
class SoinsController < ApplicationController
  def index
    @soins = Soin.all
  end

  def show
    @soin = Soin.find(params[:id])
  end

  private

  def soin_params
    params.require(:soin).permit(:name, :description, :tarif, :temoignagnes)
  end
end

app/helpers/actus_helper.rb
module ActusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ateliers_helper.rb
module AteliersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/soins_helper.rb
module SoinsHelper
end

app/views/actus/show.html.erb
<h1>Actualitée XX </h1>

app/views/ateliers/show.html.erb
<h1>Atelier XX</h1>
# appeler un lien par rapport à un id
<h2><%= @atelier.name %></h2>
<p><%= @atelier.description %></p>
<p><%= @atelier.tarif %></p>
<p><%= @atelier.temoignages %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- titre 70 caracteres max -->
    <title>Guérison : approche sciencifique et énergétique - Comment utiliser les énergies pour guérir?</title>

    <!--qui fournira à Google le texte de résumé qu'il affichera dans ses SERP : 100 min et 160 caracteres max -->
    <meta name="description" content="Pharmacienne et bioénergéticienne - L'énergie au service de notre santé. Comment utiliser les énergies pour guérir? Les hypersensibles.">

    <!--(ou noindex, nofollow, etc.) qui indiquera à Googlebot s'il doit indexer (ou pas) et suivre les liens (ou pas) de cette page -->
    <meta name="robots" content="index,follow">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
  </head>

  <body>

    <!-- navbar -->
    <aside>


    </aside>
      <input type="checkbox" id="menu-toggle"/>
        <label id="trigger" for="menu-toggle"></label>
        <label id="burger" for="menu-toggle"></label>
        <ul id="menu" style="list-style-type: outside">

          <li class ="pt-3 mt-5 mb-2">
            <a <%=link_to "HOME", root_path%></a>
          </li>

          <li class ="mb-2">
            <a <%=link_to "BIOENERGIE", bioenergie_path%></a>
          </li>

          <li class =" mb-2">
            <a <%=link_to " - Soins", soins_path%></a>
          </li>

          <li class ="mb-2" id="distance">
            <a <%=link_to " - Soins à distance", soins_a_distance_path%></a>
          </li>
          <li class ="mb-2">
            <a <%= link_to "- Animaux", animaux_path %></a>
          </li>

          <li class ="mb-2">
            <a <%= link_to "HYPERSENSIBILITE", ateliers_path %></a>
          </li>

          <li class ="mb-2">
            <a <%= link_to "COACHING", coaching_path %></a>
          </li>
          <li class ="mb-2" id="distance">
            <a <%=link_to "DR. EN PHARMACIE ", therapeute_pharmacienne_bioenergeticienne_path%></a>
          </li>
          <li class ="mb-2">
            <a <%= link_to "CONTACT", contact_path %></a>
          </li>
        </ul>

    <!--<div class="container mt-0 mb-0">
      <%= link_to root_path, :action => 'go' do %>
        <%= image_tag 'logo-bois-test.png', height: '200px', alt: "Logo Energies et Guérison"%>
      <% end %>
    </div>-->


    <!-- semi responsive navbar sans le burger qui se deploit -->
        <!--<nav>
        <nav>
        <ul class="nav-links">
          <li>
            <a <%=link_to "Home", root_path%></a>
          </li>
          <li>
            <a <%=link_to "Bioénergie", bioenergie_path%></a>
          </li>
          <li>
            <a <%=link_to "Soins", soins_path%></a>
          </li>
          <li>
            <a <%= link_to "Ateliers", ateliers_path %></a>
          </li>
          <li>
            <a <%= link_to "Activités", actus_path %></a>
          </li>
          <li>
            <a <%=link_to "Thérapeute", therapeute_pharmacienne_bioenergeticienne_path%></a>
          </li>
          <li>
            <a <%= link_to "Contact", contact_path %></a>
          </li>
        </ul>

        <div class="burger">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        </div>

      </nav>
      <script src="application.js"></script>



  <!-- grand ecran navbar -->
       <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light ">
          <div class="navbar-brand ml-2">
            <a class="navbar-brand "<%=link_to "Energies & Guérison", root_path%></a>

          </div>


          <div class="collapse navbar-collapse" >
            <div class="navbar-nav ">
              <a class="nav-item nav-link"<%=link_to "Home", root_path%></a>
              <a class="nav-item nav-link"<%=link_to "Soins", soins_path%></a>
              <a class="nav-item nav-link"<%= link_to "Ateliers", ateliers_path %></a>
              <a class="nav-item nav-link"<%= link_to "Activités", actus_path %></a>
              <a class="nav-item nav-link"<%=link_to "Thérapeute", therapeute_pharmacienne_bioenergeticienne_path%></a>
              <a class="nav-item nav-link"<%= link_to "Contact", contact_path %></a>
            </div>
          </div>

          <div class="collapse navbar-collapse navbar-nav droite" >
              <a class="nav-item nav-link ">Français</a>
              <a class="nav-item nav-link ">English</a>
          </div>

        </nav>
      </div>


        <!-- code le contenu de la page -->

      <div class= "scroll-container">
        <%= yield %>
      </div>

        <!-- Footer -->

        <footer class="footer">

          <div class="footer_line" >
          </div>



            <!-- Grid row -->
            <div class="footer-container-contact-product row mt-5">

              <!-- Grid column -->
              <div class="col-md-4 col-lg-3 col-xl-3 ml-5 ">

                <!-- Links -->

                <h6 class=" footer-heading "><%=link_to "ENERGIES ET GUERISON", root_path%></h6>

                <p class= "mb-1">
                  <a href=""><%= link_to "Bioénergie", bioenergie_path %></a>
                </p>
                 <p class= "mb-1">
                  <a href=""><%= link_to " - Soins à distance", soins_a_distance_path %></a>
                </p>
                <p class= "mb-5">
                  <a href=""><%= link_to " - Animaux", animaux_path %></a>
                </p>
              </div>


              <!-- Grid column -->
              <div class="col-md-4 col-lg-3 col-xl-3 ml-5 ">

                <!-- Links -->

                <h6 class=" footer-heading"><%=link_to "PHARMACIENNE - BIOENERGETICIENNE", therapeute_pharmacienne_bioenergeticienne_path%></h6>


                <p class= "mb-1">
                  <a href=""><%= link_to "Hypersensibilité", ateliers_path %></a>
                </p>

                <p class= "mb-5">
                  <a href=""><%= link_to "Coaching", coaching_path %></a>
                </p>
              </div>

              <!-- Grid column -->
              <div class="col-md-4 col-lg-3 col-xl-3 ml-5">

                <!-- Links -->
                <h6 class="footer-heading"><%= link_to "CONTACT", contact_path %>
                </h6>
                <!-- Facebook Links : <a href="https://www.facebook.com/Energies-et-Gu%C3%A9rison-103654888370847"><i class="fab facebook footer-social-icon fa-facebook-f"></i></a>
                  Fin Facebook link-->

                <p class= "mb-1">
                  <a href="https://www.google.ch/maps/place/Saint-Prex/@46.4659738,6.4385357,13z/data=!3m1!4b1!4m5!3m4!1s0x478c39b501ea0fe1:0xdc0de6e932131cda!8m2!3d46.4829113!4d6.4583435 ">Saint-Prex, Vaud, Suisse</a></p>
                <p class= "mb-1">
                  <a href="mailto:info@energies-et-guerison.ch">info@energies-et-guerison.ch</a></p>
                <p class= "mb-1">
                  <a href="tel:+41 76 69 06 802 ">+41 76 69 06 802</a></p>
              </div>
              <!-- Grid column -->

            </div>
            <!-- Grid row -->

          <!-- Copyright -->
          <div class="text-center copyright mt-3 pb-2">
            <p class="f-14">© 2021 Copyright par www.energies-et-guerison.ch</p>
          </div>
          <!-- Copyright -->

        </footer>
        <!-- Footer -->



      </div>

  </body>


</html>

app/views/pages/animaux.html.erb
<div class="container justify-content-center pt-5 mt-5">
  <div class="container-title banner-flex text-center justify-content-center pt-3 pb-2">
    <h1>Soins sur les animaux<br>  </h1>

  </div>
</div>

<div class="container  ">
  <div class="row justify-content-center mt-5">
    <div class="sous-titre mb-3 pt-2 mt-5">
    <h2><i class="fas fa-feather-alt ml-5 mr-3"></i>Pour votre animal de compagnie</h2>
    </div>
    <div class="soin-cards ">

      <div class="col-12 col-lg-12 ">
        <div class="soin-card text-center">

          <div class="soin-card-body">
            <h2 class="card-title">Chiens, chats, chevaux</h2>
            <%= image_tag 'animaux.jpeg', height: '150px' %>
            <p class="mt-3 card-text">De même que pour l'être humain la méthode bioénergétique Acmos est utilisée pour le soin sur votre animal.
            </p>

            <h3 class="card-text-question">Indications thérapeutiques</h3>
              <p>En cas de <strong>problème ponctuel, voire aigu,</strong> le soin donne sa pleine mesure dans une action de rétablir l'équilibre énergétique global afin de remettre en état les facultés d'auto-réparation de l'organisme.
              <br><br>Le soin chez l'animal, comme pour chez l'homme, est là pour lui permettre de retrouver ses capacités d'autogestion.
              <br><br> Recommandé pour les chiens, chats et chevaux.
              </p>

              <h3 class="card-text-question">Mécanisme d'action </h3>
                <p>Le soin repose sur le principe de base de la <strong>physique et résonance quantiques</strong> :
                <br>le corps matière de votre animal est géré par notre corps énergétique.
                Ce dernier l'informe, par les champs énergétiques, des problèmes que lui pose son corps matière dans sa dimension physique et psychique.
                <br> <br>L'<strong>information cellulaire</strong> se propage par <strong>phénomène de résonance</strong> à l'intérieur et à l'extérieur du corps de l'animal.
                    L'information se déplaçant sous forme d'ondes n'est assujettie ni au temps ni à l'espace. Elle peut être transférée <strong>instantanément à n'importe quelle distance.</strong>
                <br><br>De même que le soin sur place, le soin à distance repose sur le principe de biorésonance et l'antenne de Lecher est utilisé pour la reception et l'émission des champs énergétiques. En fonction des priorités de son corps, nous réalisons des transferts énergétiques d'huiles essentielles, de minéraux, d'oligoéléments, de phyto (plantes), d'homéopathies.
                <br><br>Ce soin agit également dans le profond, au niveau du champ centripète, siège de la <strong>cause du symptôme</strong> de votre animal.
                <br><br>
                La méthode Acmos permet de capter les informations qui sont en permanence disponibles et présentes,
                peu importe l'endroit où se trouve l'animal afin d'établir son bilan énergétique et de <strong>restaurer son équilibre global</strong>.
                <br><br> L'accès à ses informations par le biais de la méthode permet :
                  <ul>
                    <li class= " retour-ligne-list">d'apporter des <strong>corrections</strong> ou de prendre des dispositions nécessaires au rétablissement de l'équilibre,</li>
                    <li class= " retour-ligne-list">de mettre des <strong>protections contre les agressions</strong> de l'environnement, géobiologiques, ambiantes, écologiques, autres animaux...</li>
                    <li class= "retour-ligne-list">et de <strong>débloquer des situations</strong>
                  </ul>
              <h3 class="card-text-question mb-0 pb-0">Schéma thérapeutique<h3>
                 <p><br><br>Souvent le corps de l'animal a engrammé une façon de fonctionner avec différents blocages.
                  <br><br>La majorité des animaux qui consultent ont <strong>2 à 3 soins</strong> rapprochés en 6 mois. Par la suite, en général, un suivi 1 à 2 fois par an est suffisant pour maintenir l'équilibre énergétique et être dans la prévention.
                <br><br>Ce schéma thérapeutique est <strong>indicatif</strong>. Chaque animal a ses propres besoins.

                </p>
          </div>
          <h3 class="card-text-question  pb-0">Durée <h3>
              <button disabled class="button-soin  "><i class="far fa-clock mr-2 ml-2"></i> 1h15</button>

          <h3 class="card-text-question mb-4 pb-0">Tarif<h3>
            <div class = "container justify-content-center mt-4 mb-0">
              <button disabled class="button-soin mb-3"><i class="fas fa-coins mr-2"></i> 150 CHF</button>
            </div>
          <div class = "container justify-content-center mb-2 mt-4">
              <button class="button-en-savoir-plus mb-3 mr-5 "><%= link_to " En savoir plus sur la méthode Acmos", bioenergie_path %> </button>
              <button class="button-en-savoir-plus mb-3 mr-5"><%= link_to " Prendre rendez-vous", contact_path %> </button>
          </div>
        </div>

      </div>

       <div class="soin-cards">
        <div class="col-12 col-lg-12 ">
          <div class="soin-card" style="border:none;">
            <div class="soin-card-body">
              <h2 class="card-title text-center pb-0">Déroulement du soin </h2>

              <p class="card-text-question pt-2 pb-0 mb-0">Avant le soin, nous avons besoin :
                <ul class =" ml-2 mt-2"></ul>
                  <li class="ml-4 retour-ligne-list ">d'une <strong>photo</strong> de votre animal <strong>en entier </strong></li>
                  <li class="ml-4 retour-ligne-list" >de sa <strong>date de naissance, son prénom </strong>, <strong>type d'animal</strong>, race, la <strong>ville/pays</strong> où il se trouve lors du soin</li>
              </p>
              <p class="card-text-question pt-2 pb-0 mb-0">Pendant le soin :
                <ul class ="ml-2 mt-4 "></ul>
                  <li class="ml-4 retour-ligne-list">durée : 1h - l'animal doit être au calme </li>
                  <li class="ml-4 retour-ligne-list">par exemple, <strong>ne pas être monter son cheval durant le soin</strong> </li></p>
              <p class="card-text-question pt-2 pb-0 mb-0">Après le soin :
                <ul class ="ml-2 mt-4"></ul>
                  <li class="ml-4 retour-ligne-list">durée : 10 minutes - explication par téléphone<sup>*</sup> des points travaillés pendant le soin.</li>

                  <li class="ml-4 retour-ligne-list">pour finaliser le traitement, en fonction des besoins de votre animal, il devra potentiellement prendre des produits (homéopathie le plus souvent) </li>
                  <li class="ml-4 retour-ligne-list">pour ce faire, une fiche de suivi vous est délivrée. </li>

              <p class="mt-1" style="text-align: left"><sup>*</sup>Pour les soins internationaux, seul whatsapp et signal sont utilisés.

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container  ">
  <div class="row justify-content-center mt-0 pt-0">
    <div class="sous-titre mb-3 pt-2 mt-5">
    <h2><i class="fas fa-feather-alt ml-5 mr-3"></i>Pour tout autre animal</h2>
    </div>
    <div class="soin-cards ">
      <%= link_to contact_path, :action => 'go' do %>
      <div class="col-12 col-lg-12 ">
        <div class="soin-card-contact text-center">

          <div class="soin-card-body">
            <h2 class="card-title">Nous contacter </h2>

            <p class="mt-3 card-text">De même que pour les autres animaux, la base du soin se déroule de manière identique afin que votre animal retrouve ses capacités d'autogestion.
              <br><br>Pour répondre au mieux à votre demande, pour les <strong>vaches, moutons, chèvres</strong> ... merci de nous contacter afin de vous proposer une solution adaptée.</p>
          </div>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="soin-cards mb-5">

      <div class="col-12 col-lg-12 ">

          <div class="soin-card-body">
            <h4 class=" card-text pt-0">Pour rappel, les soins et bilans ne remplacent ni un suivi, ni un traitement vétérinaire.
            </h4>
          </div>


      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<h1>produit xx XX vraiment utile ?</h1>
# appeler un lien par rapport à un id



<%= link_to "Tous les produits", products_path %>

app/views/soins/index.html.erb
<div class="container justify-content-center pt-5 mt-5 mb-4">
  <div class="container-title banner-flex text-center justify-content-center pt-3 pb-2">
    <h1>Soins</h1>

  </div>
</div>

  <!-- code 1ere ligne soins  -->
<div class="container">


    <div class="soin-cards">

      <div class="col-12 col-lg-12">

        <div class="soin-card text-center">

            <div class="soin-card-body">

              <h2 class="card-title">Bilans bioénergétiques Acmos</h2>
              <%= image_tag 'cabinet_radius.jpeg', height: '100px' %>
              <h3 class="card-text-question">Indications thérapeutiques</h3>
                <p>Vous êtes fatigués, stressés, déprimés ou avez des maux physiques comme des maux de dos, migraines.. ?
                <br><br>Votre enfant est fatigué, anxieux, a du mal à se concentrer, à s'endormir, à trouver de la motivation ?
                <br><br> <strong>Synergie</strong> entre la <strong>médecine traditionnelle</strong> et la <strong>médecine quantique</strong>.
                <br><br> S'adresse aux enfants<sup>*</sup> et aux adultes.
              </p>

              <h3 class="card-text-question">Mécanisme d'action </h3>
                <p>La Méthode Acmos a pour objet de permettre au corps de reprendre le contrôle de ses circuits énergétiques afin qu'il retrouve sa capacité d'autogestion. </p>
                <p>Aujourd'hui, la médecine contemporaine s'attache à régler les désordres indiqués et confirmés par les analyses scientifiques (radiologie, IRM, chimie etc...). Ces indications, issues du corps, sont d'ordre essentiellement symptomatiques.

                <br><br>La Méthode Acmos <strong>ne s'arrête pas aux symptômes</strong> qui ne sont que de simples indicateurs de désordres provoqués
              par un problème plus profond.
              Elle s'attachera plutôt à <strong>détecter la cause afin de la corriger</strong>, en se basant sur des découvertes issues de la médecine quantique.

              <h3 class="card-text-question mb-0 pb-0">Schéma thérapeutique<h3>
                 <p><br><br>Souvent notre corps a engrammé une façon de fonctionner avec différents blocages.
                  <br><br>La majorité des personnes qui consultent ont <strong>2 à 3 soins</strong> rapprochés <strong>en 6 mois</strong>.
                  <br><br>Puis, pour être dans un mode <strong>préventif</strong> en <strong>maintenant un équilibre énergétique optimal</strong> et que notre corps ne soit pas impacté par les perturbateurs énergétiques (travail, stress, contexte familial, couple, situation écnomique, pandémie),

                   il est recommandé de réaliser un suivi saisonnier - <strong>1 consultation par saison</strong>.
                <br><br>Ce schéma thérapeutique est <strong>indicatif</strong>. Chaque individu a ses propres besoins.

                <br><br>En pratique : le premier soin peut être réalisé au <strong>cabinet ou à distance</strong>.
                Souvent, les soins suivants sont réalisés <strong>à distance</strong>.</p>

            </div>

            <h3 class="card-text-question  pb-0">Durée <h3>
              <button disabled class="button-soin  "><i class="far fa-clock mr-2 ml-2"></i> 1h</button>

            <h3 class="card-text-question mb-4 pb-0">Tarif<h3>
              <div class = "container justify-content-center mt-4 mb-0">
                <button disabled class="button-soin mb-3 ">Adulte <i class="fas fa-coins ml-2 mr-2"></i> 150 CHF <br><br> Enfant <i class="fas fa-coins ml-2 mr-2"></i> 120 CHF</button>
              </div>

              <div class = "container justify-content-center mb-2 mt-4">
                <button class="button-en-savoir-plus mb-3 mr-5 "><%= link_to " En savoir plus sur la méthode Acmos", bioenergie_path %> </button>
                <button class="button-en-savoir-plus mb-3 mr-5"><%= link_to " Découvrez nos soins à distance", soins_a_distance_path %> </button>
                <button class="button-en-savoir-plus mb-3 "><%= link_to " Prendre rendez-vous", contact_path %> </button>
              </div>

            <p><sup>*</sup>Les soins chez les enfants se font uniquement avec la présence d'un parent.</p>

      </div>
    </div>


    <div class="soin-cards">
        <div class="col-12 col-lg-12 ">
          <div class="soin-card" style="border:none;">
            <div class="soin-card-body">
              <h2 class="card-title text-center pb-0">Déroulement du soin </h2>

              <p class="card-text-question pt-2 pb-0 mb-0">Avant le soin :
                <ul class =" ml-2 mt-2"></ul>
                  <li class="ml-4 retour-ligne-list ">le jour précédent le bilan : ne pas boire d'alcool et privilégier une alimentation légère</li>
                  <li class="ml-4 retour-ligne-list" >pour le soin, mettre des vêtements confortables</li>
                  <li class="ml-4 retour-ligne-list">venir avec vos médicaments et <strong>compléments alimentaires</strong> que vous prenez usuellement afin de tester la compatibilité énergétique et définir un éventuel compensateur énergétique</li></p>
              <p class="card-text-question pt-2 pb-0 mb-0">Pendant le soin :
                <ul class ="ml-2 mt-4 "></ul>
                  <li class="ml-4 retour-ligne-list">durée : 1h - profitez de ce moment pour vous détendre </li>
                  <li class="ml-4 retour-ligne-list">une première partie est dédiée à <strong>l'anamnèse</strong> (échange sur les symptômes), puis le soin se déroule sur une table de soin où les <strong>mesures et transferts énergétiques</strong> sont réalisés</li></p>
              <p class="card-text-question pt-2 pb-0 mb-0">Après le soin :
                <ul class ="ml-2 mt-4"></ul>
                  <li class="ml-4 retour-ligne-list">félicitations! Après le soin, 60% du travail est réalisé.</li>
                  <li class="ml-4 retour-ligne-list">à partir de maintenant, pour finaliser le traitement, les <strong>40 % restants</strong>, il vous faut prendre ce que votre corps a demandé durant le soin </li>
                  <li class="ml-4 retour-ligne-list">pour ce faire, une <strong>fiche de suivi</strong> vous est délivrée afin de savoir quel(s) produit(s) votre corps a demandé lors du soin </li>
                  <li class="ml-4 retour-ligne-list">durant les 24h qui suivent le soin: bien s'hydrater, ne pas boire d'alcool et privilégier une alimentation légère</li>


              <p class="card-text-question pt-2 pb-0 mb-2">Où trouver les produits :
                  <p class="acmos-link" >Les oligoéléments et homéopathies peuvent être à acheter dans <strong>la pharmacie</strong> de votre village, quartier
                    <br>D'autres produits se commandent auprès d'<strong>Acmos-sbj</strong> : <a href="https://www.acmos-sbj.com/phytotherapie-_l_FR_r_53.html" target="_blank"> phytothérapie</a>, <a href="https://www.acmos-sbj.com/filtres-de-couleur-_l_FR_r_49.html" target="_blank"> <strong>chromothérapie</strong></a>, <a href="https://www.acmos-sbj.com/mineraux-_l_FR_r_52_va_1.html" target="_blank"> minéraux</a>, <a href="https://www.acmos-sbj.com/complexes-saisonniers-_l_FR_r_69.html" target="_blank">complexes saisonniers</a> ainsi que  <a href="https://www.acmos-sbj.com/huiles-essentielles-_l_FR_r_48.html" target="_blank">huiles essentielles</a>. </p>


              </p>
            </div>
          </div>
        </div>
  </div>
</div>


<!-- code  soins 2ème ligne  -->



<div class="container mb-2">
  <div class="row justify-content-center">
    <div class="soin-cards ">

      <div class="col-12 col-lg-12 ">

          <div class="soin-card-body">
            <h4 class=" card-text pt-0">Pour rappel, les soins et bilans ne remplacent ni un suivi, ni un traitement médical. Aucune modification de votre traitement ne sera réalisée.
              <br><br> Dans le cadre du covid-19, dans la mesure où les soins à distance ont la même efficacité que les soins sur place, les soins à distance sont privilégiés.</h4>
          </div>


      </div>
    </div>
  </div>
</div>

app/views/soins/show.html.erb
<h1>Soin XX</h1>
# appeler un lien par rapport à un id
<h2><%= @soin.name %></h2>
<p><%= @soin.description %></p>
<p><%= @soin.tarif %></p>
<p><%= @soin.temoignages %></p>